### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [sickel/qgisspectrereader#1]
Please populate the links properly in metadata.txt and also a little description would help. 

Please also explain plugin usefulness. Are you not going to be loading the data using gdal and what is different from using the data source manager, browser and DB manager

**Comment by pcav** [comment]
Could you please let us know when done?
Thanks.

**Comment by sickel** [comment]
Uploaded new version. The reaseon for this plugin is to be able to structure fields with a spectra into a  single array or comma separated string as having a spectra split into one field per channel is unmanageable.  It is also reading a data structure where each point is a single text file.

**Comment by NyakudyaA** [comment]
@sickel the issuer tracker link still doesn't point to the issues link https://github.com/sickel/qgisspectrereader/blob/master/metadata.txt#L15

**Comment by pcav** [comment]
I think it's OK now. If I'm missing something, please @NyakudyaA unapprove it.
Cheers.
